---
- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: yes

- name: restart kibana
  systemd:
    name: kibana
    state: restarted
    daemon_reload: yes

- name: restart logstash
  systemd:
    name: logstash
    state: restarted
    daemon_reload: yes

- name: Restart rsyslog
  systemd:  # Changed from 'service' to 'systemd'
    name: rsyslog
    state: restarted
    daemon_reload: yes

